#!/usr/bin/env python3
"""Plot raw policy outputs and operator restart markers from a policy action JSONL log.

Expected input:
- JSONL written by run_vla_policy.py --log-actions-jsonl

Outputs:
- policy_action_log_plot.png by default

The figure contains:
- one subplot per joint for model_raw_joint_positions_rad
- a gripper subplot for model_raw_gripper with the 0.5 threshold line
- vertical event markers for rehome / resume / shutdown
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


JOINT_ACTION_DIM = 7
EVENT_STYLES = {
    "operator_rehome_requested": {"color": "tab:red", "linestyle": "--", "label": "rehome requested"},
    "operator_resume_requested": {"color": "tab:green", "linestyle": "--", "label": "resume requested"},
    "operator_shutdown_requested": {"color": "tab:gray", "linestyle": ":", "label": "shutdown requested"},
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--jsonl",
        type=Path,
        required=True,
        help="Path to the policy action JSONL log generated by run_vla_policy.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output PNG path. Defaults to <jsonl stem>_plot.png next to the input file.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show the plot interactively in addition to saving it.",
    )
    return parser.parse_args()


def iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no}: invalid JSON: {exc}") from exc
            if not isinstance(row, dict):
                raise ValueError(f"{path}:{line_no}: expected JSON object")
            yield line_no, row


def timestamp_from_row(row: dict[str, Any]) -> int:
    value = row.get("timestamp_ns")
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    raise ValueError("missing timestamp_ns")


def extract_joint_series(row: dict[str, Any]) -> list[float] | None:
    raw = row.get("model_raw_joint_positions_rad")
    if isinstance(raw, list) and len(raw) == JOINT_ACTION_DIM:
        return [float(v) for v in raw]

    fallback = row.get("raw_joint_positions_rad")
    if isinstance(fallback, list) and len(fallback) >= JOINT_ACTION_DIM:
        return [float(v) for v in fallback[:JOINT_ACTION_DIM]]
    return None


def extract_raw_gripper(row: dict[str, Any]) -> float | None:
    value = row.get("model_raw_gripper")
    if isinstance(value, (int, float)):
        return float(value)
    fallback = row.get("raw_gripper")
    if isinstance(fallback, (int, float)):
        return float(fallback)
    return None


def load_log(path: Path):
    action_times_ns: list[int] = []
    joint_rows: list[list[float]] = []
    raw_gripper: list[float] = []
    latched_gripper: list[float] = []
    event_times_ns: dict[str, list[int]] = {key: [] for key in EVENT_STYLES}

    for line_no, row in iter_jsonl(path):
        try:
            timestamp_ns = timestamp_from_row(row)
        except ValueError as exc:
            raise ValueError(f"{path}:{line_no}: {exc}") from exc

        record_type = row.get("record_type")
        if record_type == "event":
            event_type = row.get("event_type")
            if isinstance(event_type, str) and event_type in event_times_ns:
                event_times_ns[event_type].append(timestamp_ns)
            continue

        joints = extract_joint_series(row)
        gripper = extract_raw_gripper(row)
        if joints is None or gripper is None:
            continue
        action_times_ns.append(timestamp_ns)
        joint_rows.append(joints)
        raw_gripper.append(gripper)
        latched_gripper.append(row.get("latched_gripper_command"))

    if not action_times_ns and not any(event_times_ns.values()):
        raise RuntimeError(f"No plottable action or event rows found in {path}")

    t0_ns = min(
        [*action_times_ns, *[timestamp for values in event_times_ns.values() for timestamp in values]]
    )
    action_t_s = (np.asarray(action_times_ns, dtype=np.float64) - float(t0_ns)) * 1e-9
    joint_array = np.asarray(joint_rows, dtype=np.float64) if joint_rows else np.empty((0, JOINT_ACTION_DIM))
    gripper_array = np.asarray(raw_gripper, dtype=np.float64) if raw_gripper else np.empty((0,), dtype=np.float64)
    latched_gripper_array = np.asarray(latched_gripper, dtype=np.float64) if latched_gripper else np.empty((0,), dtype=np.float64)
    event_t_s = {
        event: (np.asarray(times, dtype=np.float64) - float(t0_ns)) * 1e-9
        for event, times in event_times_ns.items()
    }
    return action_t_s, joint_array, gripper_array, latched_gripper_array, event_t_s


def add_event_markers(ax, event_t_s: dict[str, np.ndarray]) -> None:
    used_labels: set[str] = set()
    for event_type, times in event_t_s.items():
        style = EVENT_STYLES[event_type]
        label = style["label"]
        for index, t_s in enumerate(times):
            ax.axvline(
                t_s,
                color=style["color"],
                linestyle=style["linestyle"],
                alpha=0.8,
                linewidth=1.2,
                label=label if label not in used_labels and index == 0 else None,
            )
        if times.size > 0:
            used_labels.add(label)


def style_axis(ax, ylabel: str) -> None:
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.3)


def add_legend(ax) -> None:
    handles, labels = ax.get_legend_handles_labels()
    if handles:
        ax.legend(loc="upper right", fontsize=8, ncol=2)

def make_figure(action_t_s: np.ndarray, joint_array: np.ndarray, gripper_array: np.ndarray, latched_gripper_array: np.ndarray, event_t_s: dict[str, np.ndarray]):
    fig, axes = plt.subplots(JOINT_ACTION_DIM + 1, 1, figsize=(16, 20), sharex=True)

    for joint in range(JOINT_ACTION_DIM):
        ax = axes[joint]
        if joint_array.size > 0:
            ax.plot(action_t_s, joint_array[:, joint], color=f"C{joint % 10}", label=f"joint_{joint}")
        add_event_markers(ax, event_t_s)
        style_axis(ax, f"J{joint} [rad]")
        add_legend(ax)

    gripper_ax = axes[-1]
    if gripper_array.size > 0:
        gripper_ax.plot(action_t_s, gripper_array, color="tab:purple", label="raw_gripper")
        gripper_ax.plot(action_t_s, latched_gripper_array, color="tab:blue", label="latched_gripper")
        gripper_ax.axhline(0.5, color="black", linestyle=":", alpha=0.8, label="threshold=0.5")
    add_event_markers(gripper_ax, event_t_s)
    style_axis(gripper_ax, "Gripper")
    gripper_ax.set_xlabel("Time [s]")
    add_legend(gripper_ax)
    # gripper_ax.set_xlim(0,50)

    fig.suptitle("Policy Raw Outputs and Rehome/Resume Markers")
    fig.tight_layout()
    return fig


def main() -> int:
    args = parse_args()
    output_path = args.output
    if output_path is None:
        output_path = args.jsonl.with_name(f"{args.jsonl.stem}_plot.png")

    action_t_s, joint_array, gripper_array, latched_gripper_array, event_t_s = load_log(args.jsonl)
    fig = make_figure(action_t_s, joint_array, gripper_array, latched_gripper_array, event_t_s)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150)
    print(f"Saved plot: {output_path}", flush=True)

    if args.show:
        plt.show()
    else:
        plt.close(fig)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
